export const QUOTES: { text: string; author: string }[] = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Stay hungry, stay foolish.", author: "Stewart Brand" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Whether you think you can or you can't, you're right.", author: "Henry Ford" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "He who has a why can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Slow is smooth, smooth is fast.", author: "Navy SEALs" },
  { text: "Begin where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Memento mori.", author: "Stoic" },
  { text: "Amor fati.", author: "Nietzsche" },
];
