export const QUOTES: { text: string; author: string }[] = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Stay hungry, stay foolish.", author: "Stewart Brand" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Whether you think you can or you can't, you're right.", author: "Henry Ford" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "He who has a why can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Slow is smooth, smooth is fast.", author: "Navy SEALs" },
  { text: "Begin where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Memento mori.", author: "Stoic" },
  { text: "Amor fati.", author: "Nietzsche" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "You miss 100 percent of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "Work hard in silence, let success be your noise.", author: "Frank Ocean" },
  { text: "Excellence is never an accident.", author: "Aristotle" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "You become what you believe.", author: "Oprah Winfrey" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { text: "Fall in love with the process and the results will come.", author: "Eric Thomas" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "If the plan doesn't work, change the plan but never the goal.", author: "Unknown" },
  { text: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.", author: "John C. Maxwell" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "If you're offered a seat on a rocket ship, don't ask what seat.", author: "Sheryl Sandberg" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Do not pray for easy lives. Pray to be stronger men.", author: "John F. Kennedy" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "If it matters to you, you will find a way.", author: "Charlie Gilkey" },
  { text: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
  { text: "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.", author: "Francis of Assisi" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "The harder the conflict, the greater the triumph.", author: "George Washington" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Big things have small beginnings.", author: "Francis Ford Coppola" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { text: "Be stubborn about your goals and flexible about your methods.", author: "Unknown" },
  { text: "Nothing works unless you do.", author: "Maya Angelou" },
  { text: "Your limitation, it's only your imagination.", author: "Unknown" },
  { text: "You are your only limit.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Dreams don't work unless you do.", author: "John C. Maxwell" },
  { text: "Sometimes later becomes never. Do it now.", author: "Unknown" },
  { text: "Little progress each day adds up to big results.", author: "Satya Nani" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Marilyn Monroe" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Success is the sum of efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Consistency beats intensity.", author: "Unknown" },
  { text: "Direction is more important than speed.", author: "Unknown" },
  { text: "You can't control the wind, but you can adjust your sails.", author: "Dolly Parton" },
  { text: "The comeback is always stronger than the setback.", author: "Unknown" },
  { text: "Stay patient and trust your journey.", author: "Unknown" },
  { text: "Growth is uncomfortable because you've never been here before.", author: "Kristin Lohr" },
  { text: "Your habits will shape your future.", author: "Jack Canfield" },
  { text: "Make it happen. Shock everyone.", author: "Unknown" },
  { text: "Winners focus on winning. Losers focus on winners.", author: "Unknown" },
  { text: "Don't lower your goal. Increase your effort.", author: "Tom Coleman" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "If it doesn't challenge you, it won't change you.", author: "Fred DeVito" },
  { text: "Work until your introduction is no longer necessary.", author: "Unknown" },
  { text: "Success starts with self-belief.", author: "Unknown" },
  { text: "Fear kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Success is no accident.", author: "Pele" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { text: "Never bend your head. Always hold it high.", author: "Helen Keller" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "When one door closes, another opens.", author: "Alexander Graham Bell" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "No pressure, no diamonds.", author: "Thomas Carlyle" },
  { text: "Believe you can and you are halfway there.", author: "Theodore Roosevelt" },
  { text: "If you want the light to come into your life, you need to stand where it is shining.", author: "Guy Finley" },
  { text: "Stars can't shine without darkness.", author: "D.H. Sidebottom" },
  { text: "Failure is not the opposite of success; it is part of success.", author: "Arianna Huffington" },
  { text: "Suffering is a gift. In it is hidden mercy.", author: "Rumi" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
];
